osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
    - icnsutils
    - graphicsmagick

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

before_script:
  - npm install -g @angular/cli
  - npm install

script:

  - echo 'Build Dist' && echo -en 'travis_fold:start:script.build\\r'

  - ng build --base-href="./"

  - echo -en 'travis_fold:end:script.build\\r'
  - echo 'Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'

  - npm run lint

  - echo -en 'travis_fold:end:script.lint\\r'
  - echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'

  - ng test --single-run --code-coverage

  - echo -en 'travis_fold:end:script.test\\r'
  - echo 'Package Dist' && echo -en 'travis_fold:start:script.dist\\r'

  - cd dist
  - zip -r $TRAVIS_BUILD_DIR/dist.zip *

  - cd $TRAVIS_BUILD_DIR
  - sha256sum $TRAVIS_BUILD_DIR/dist.zip > $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
  - cat $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt

  - echo -en 'travis_fold:end:script.dist\\r'

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package:linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package:win && npm run package:mac; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

after_script:
  - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
